version: 2
jobs:
  build:
    docker:
      - image: alpine:3.7
    working_directory: circleci-primes
    steps:
      - checkout
      - run: apk add bc
      - run: ./nextprime.sh
      - run: echo "The next prime is $( tail -n 1 primes.txt )."
      - run: git commit -am 'Add $( tail -n 1 primes.txt ) to prime list.'
      - run: git push
