version: 2
jobs:
  build:
    docker:
      - image: alpine:3.7
    working_directory: /src/circleci-primes
    steps:
      - checkout
      - add_ssh_keys
      - run: apk add bc git openssh
      - run: ./nextprime.sh
      - run: echo "The next prime is $( tail -n 1 primes.txt )."
      - run: git config --global user.email "CircleCI@CircleCI.com"
      - run: git config --global user.name "CircleCI"
      - run: git commit -am 'Add $( tail -n 1 primes.txt ) to prime list.'
      - run: >
        echo '
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        ' >> ~/.ssh/known_hosts
      # - run: git push origin HEAD:master
