version: 2
jobs:
  build:
    docker:
      - image: alpine:3.7
    working_directory: /src/circleci-primes
    steps:
      - checkout
      - run: apk add bc git
      - run: ./nextprime.sh
      - run: echo "The next prime is $( tail -n 1 primes.txt )."
      - run: git config --global user.email "CircleCI@CircleCI.com"
      - run: git config --global user.name "CircleCI"
      - run: git commit -am 'Add $( tail -n 1 primes.txt ) to prime list.'
      - run: git push
